# Generated by Django 4.1.1 on 2022-09-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='reference_number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
